### ISSUE TITLE
Use it in a docker compose file

### ISSUE THREAD

**Issue by sp90** [kingsquare/docker-tunnel#2]
Hey kingsquare nice tool,

I would love to have this working in docker-compose have you tested it out:

right now i have the following config:

``` yaml
dbtunnel:
  container_name: dbtunnel
  image: tunnel (my own build of your container)
  volumes: 
    - $SSH_AUTH_SOCK:/ssh-agent
  command: 0.0.0.0:9200:192.168.3.10:9200 -L 0.0.0.0:15432:192.168.3.16:5432 -L 0.0.0.0:25432:192.168.3.19:5432 -L 0.0.0.0:6379:192.168.3.16:6379 -vvvv user@example.com
```
