### ISSUE TITLE
Is it possible to use "Reverse Tunnelling" (-R) with this image?

### ISSUE THREAD

**Issue by phlegx** [kingsquare/docker-tunnel#3]
Running the following tunnel command from localhost to my remote server, allows me to access my local app that is running on port 8080 remotely on my server on port 5000:

`ssh -R 5000:localhost:8080 example.com`

Is this possible also with `docker-tunnel` if yes how? I currently tried the following (docker-compose syntax), which unfortunately fails:

```
  tunnel_app:
    image: kingsquare/tunnel:latest
    command: "-R 5000:127.0.0.1:8080 example.com"
    volumes:
      - $SSH_AUTH_SOCK:/ssh-agent
```

The error it throws is the following:

```
 Bad local forwarding specification '-R'
```

thanks in advance!
